theme: jekyll-theme-minimal
title: Welcome to Keith's homepage
description: Feel free to bookmark this to keep an eye on my project updates
name: Keith Ma
email: xma39@hawk.iit.edu
github: github.com/keith0920 
